Repository rematch/rematch, pull requests merged in 2018-03, with the labels that each got.

#235 closes #220. Add Migration guide
  README.md
  SUMMARY.md
Labels: docs

#236 Reducers that can listen to other model actions
  CHANGELOG.md
  docs/api.md
  package-lock.json
  package.json
  src/index.ts
  src/plugins/dispatch.ts
  src/redux/reducers.ts
  src/redux/store.ts
  src/utils/deprecate.ts
  src/utils/isListener.ts
  test/dispatch.test.js
  test/listener.test.js
  test/store.test.js
Labels: enhancement, plugin

#247 fix issue with enhancers
  src/redux/store.ts
Labels: bug

#251 Fix TypeScript Typings
  typings/rematch/index.d.ts
Labels: enhancement, help wanted

#249 add example with vuejs-redux
  README.md
  docs/recipes/vue.md
Labels: docs

#289 Update pluginsApi.md
  docs/pluginsApi.md
Labels: docs

#281 Add action creators to redux-devtools
  src/init.ts
  src/utils/getActionCreators.ts
Labels: enhancement

#307 Fix/android
  examples/react/count/package-lock.json
  package-lock.json
  package.json
  rollup.config.js
  src/init.ts
  src/utils/getActionCreators.ts
  tslint.json
Labels: bug

#311 effect actions not firing
  CHANGELOG.md
  examples/react/count/package-lock.json
  examples/react/count/src/models.js
  package-lock.json
  package.json
  plugins/loading/test/loading-asBoolean.test.js
  plugins/loading/test/loading-asNumber.test.js
  src/init.ts
  src/model.ts
  src/plugins/dispatch.ts
  src/plugins/effects.ts
  src/utils/buildPlugins.ts
  test/dispatch.test.js
  test/effects.test.js
Labels: bug
